version: "3.8"

services:

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka-kraft
    ports:
      - "9092:9092"     # For internal container-to-container
      - "29092:29092"   # For host-to-container access
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-kraft:9093
      - KAFKA_KRAFT_CLUSTER_ID=kraft-cluster-12345
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kraft_data:/bitnami/kafka
  mongo:
    image: mongo:6.0
    ports: ["27017:27017"]

  spark-streaming:
    build: .
    command: spark-submit --packages org.mongodb.spark:mongo-spark-connector_2.12:10.2.0,org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.0 /app/stream_app/main.py
    depends_on: [kafka, mongo]
    volumes:
      - ./data:/app/output

  spark-weekly:
    build: .
    command: spark-submit 
          --packages org.mongodb.spark:mongo-spark-connector_2.12:10.2.0
          /app/batch_weekly/weekly_job.py
    volumes:
      - ./data:/app/data

  spark-mood-predictor:
    build: .
    command: spark-submit
      --packages org.mongodb.spark:mongo-spark-connector_2.12:10.2.0
      /app/batch_kaggle/mood_predictor.py
    volumes:
      - ./data:/app/data
volumes:
  kraft_data: